# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('shortcut', models.CharField(default='', max_length=300)),
                ('category', models.CharField(default='', max_length=100)),
                ('showinlist', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('createdTime',),
            },
        ),
    ]
