# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171106_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
    ]
