# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.IntegerField(default=1)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.AlterModelOptions(
            name='bloginfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogtotag',
            options={'ordering': ('blogid',)},
        ),
    ]
