# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171113_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopBlog',
        ),
        migrations.AddField(
            model_name='bloginfo',
            name='ontop',
            field=models.BooleanField(default=False),
        ),
    ]
