# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171114_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloginfo',
            name='showinlist',
        ),
    ]
